### ISSUE TITLE
Firebase issue with firestore data not showing up

### ISSUE THREAD

**Issue by ScriptedRain** [ScriptedRain/Vybe#1]
![image](https://user-images.githubusercontent.com/71009876/116233703-fa3e7280-a79e-11eb-9609-fff925c11e32.png)
it says this in the console, it should be logging in the word "rain" which is a field from firestore, perhaps this is a issue with the api key

**Comment by krishp058** [comment]
![image](https://user-images.githubusercontent.com/74632222/116239579-290c1700-a7a6-11eb-896a-78330fbbe950.png)

It works perfectly fine for me. Also I did `npm i` then it said I have 7 vulnerabilities so then I did `npm audit fix`, it then fixed 6 of them, and at last I ran the server to test by  doing `npm start`, and everything was working as is.

**Comment by ScriptedRain** [comment]
you just had to restart server
