### ISSUE TITLE
App is not importing 

### ISSUE THREAD

**Issue by ScriptedRain** [ScriptedRain/Vybe#2]
![image](https://user-images.githubusercontent.com/71009876/116356917-3cb78c00-a83f-11eb-9d96-f9e1e95517d9.png)
coming up with this when i try to import app.jsx

**Comment by krishp058** [comment]
After looking into the src and components folder I found out a possible reason that caused this. The app.jsx is in src/components/App then its app.jsx but I think you only entered the components folder not the App folder.

**Comment by krishp058** [comment]
I changed all the export methods to fix this issue, before it was `export default [file]` at end of each file, I changed it to `export const [file]`, so basically I exported it from where the variable was declared.

**Comment by ScriptedRain** [comment]
please create a commit and push it so i can pull it.
